### ISSUE TITLE
cannot make it work .. 

### ISSUE THREAD

**Issue by blahmbah** [tehmaze/classified#1]
tried to make this work on Oracle Linux 6.6  (Python 2.6.6) .. failed .. 
tried 1.3.1 release and 1.3.0 ..

release build with no erros .. and installs fine ..  make test fails .. (one reason is that classified.conf canot be found , and also there is no _platform.so in path at this time ) ..

running 
bin/classified -c etc/classified.conf.sample testdata/ 
fails
<code>
Traceback (most recent call last):
  File "bin/classified", line 94, in <module>
    sys.exit(run())
  File "bin/classified", line 81, in run
    config = Config(option.config)
  File "/usr/lib64/python2.6/site-packages/classified/config.py", line 20, in **init**
    raise IOError('Could not open {} for reading'.format(filename))
ValueError: zero length field name in format
</code>
running 
 bin/classified -c etc/classified.conf.sample -r -R tty  testdata/
fails with 
<code>
Traceback (most recent call last):
  File "bin/classified", line 94, in <module>
    sys.exit(run())
  File "bin/classified", line 81, in run
    config = Config(option.config)
  File "/usr/lib64/python2.6/site-packages/classified/config.py", line 20, in **init**
    raise IOError('Could not open {} for reading'.format(filename))
ValueError: zero length field name in format
</code>
then 
bin/classified -c etc/classified.conf.sample -r -R html -o test.html testdata/
<code>
Traceback (most recent call last):
  File "bin/classified", line 94, in <module>
    sys.exit(run())
  File "bin/classified", line 81, in run
    config = Config(option.config)
  File "/usr/lib64/python2.6/site-packages/classified/config.py", line 20, in **init**
    raise IOError('Could not open {} for reading'.format(filename))
ValueError: zero length field name in format
</code>

**Comment by mdklapwijk** [comment]
Seems to me that it is not compatible with Python 2.6 anymore.

**Comment by tehmaze** [comment]
Target Python version is 2.7 or 3.4+
